### ISSUE TITLE
Git is awesome

### ISSUE THREAD

**Issue by axios047** [vipulgupta2048/vanilla#3]

**Comment by axios047** [comment]
Tell me why git is awesome

**Comment by nishutosh** [comment]
cause git users are cool buddy

**Comment by axios047** [comment]
Oh ! Thats nice. I always wanted to be cool.

**Comment by nishutosh** [comment]
it really changes your life magic....

**Comment by axios047** [comment]
Wow I am going to use it everyday now!

**Comment by nishutosh** [comment]
every hour...every second buddy

**Comment by axios047** [comment]
Tell me some features that GIT has.

**Comment by harsh0chaudhary** [comment]
bhaiya bolenge FeAtUrEs :P

**Comment by vipulgupta2048** [comment]
@axios047  That you should. 
@nishutosh  If using git, makes you cool. Then what is edm-tour for. #justsayin
@harsh0chaudhary A slide I didn't include were rules for learning git. There you will meet a special friend. Ask him for the features. 

link for the slides- https://docs.google.com/presentation/d/1dLshLydrBL8t_X3nvOodi-LkH8iORocy8uadGrlslGc/edit?usp=sharing
